java_library(
    name = "rules_jvm_external",
    srcs = glob(["*.java"]),
    javacopts = [
        "--release",
        "8",
    ],
    visibility = [
        "//private/tools/java:__subpackages__",
    ],
)
