load("@bazel_skylib//rules:build_test.bzl", "build_test")

build_test(
    name = "starlark_aar_import_test",
    targets = [
        "@starlark_aar_import_test//:com_android_support_appcompat_v7_28_0_0",
    ],
)

build_test(
    name = "starlark_aar_import_with_jetify_test",
    targets = [
        "@starlark_aar_import_with_jetify_test//:com_android_support_appcompat_v7_28_0_0",
    ],
)
