/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.bazelbuild.rules_jvm_external.resolver.gradle.plugin;

import javax.inject.Inject;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.tooling.provider.model.ToolingModelBuilderRegistry;

public class CustomModelInjectionPlugin implements Plugin<Project> {
  private final ToolingModelBuilderRegistry registry;

  @Inject
  public CustomModelInjectionPlugin(ToolingModelBuilderRegistry registry) {
    this.registry = registry;
  }

  public void apply(Project project) {
    if (project.equals(project.getRootProject())) {
      registry.register(new OutgoingArtifactsModelBuilder());
    }
  }
}
