load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts=[
        "com.google.inject:guice:4.0", "com.google.guava:guava:27.1-jre"
    ],
    repositories=[
        "https://repo1.maven.org/maven2",
    ],
)

http_archive(
    name = "bazel_common",
    strip_prefix = "bazel-common-f1115e0f777f08c3cdb115526c4e663005bec69b",
    url = "https://github.com/google/bazel-common/archive/f1115e0f777f08c3cdb115526c4e663005bec69b.zip",
)

BAZEL_SKYLIB_TAG = "0.6.0"

http_archive(
    name="bazel_skylib",
    strip_prefix="bazel-skylib-%s" % BAZEL_SKYLIB_TAG,
    url="https://github.com/bazelbuild/bazel-skylib/archive/%s.tar.gz" %
    BAZEL_SKYLIB_TAG,
)
