exports_files([
    "manifest_stamp_testing_install.json",
    "maven_install.json",
    "policy_pinned_testing_install.json",
    "regression_testing_install.json",
    "unsafe_shared_cache_with_pinning_install.json",
])
