exports_files([
    "manifest_stamp_testing_install.json",
    "maven_install.json",
    "policy_pinned_testing_install.json",
    "regression_testing_install.json",
    "m2local_testing_with_pinned_file_install.json",
])
