load("//settings:stamp_manifest.bzl", "stamp_manifest")

package(
    default_visibility = ["//visibility:public"],
)

exports_files(["stamp_manifest.bzl"])

stamp_manifest(
    name = "stamp_manifest",
    build_setting_default = False,
)
