local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("//:set_license_classifier.bzl", "use_default_license_classifier")

use_default_license_classifier()

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()
