# This package contains static executables used by the maven_install repository rule.

exports_files([
    "hasher_deploy.jar",  # built from //private/tools/java:hasher_deploy.jar
    "list_packages_deploy.jar",  # build from //private/tools/java/rules/jvm/external/jar:ListPackages_deploy.jar
    "outdated_deploy.jar",  # built from //private/tools/java/rules/jvm/external/maven:outdated_deploy.jar
])
