load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(name = "androidsdk")

local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    pinned_maven_install = "//:pinned_maven_install.json",
)

# bazel-skylib 0.8.0 released 2019.03.20 (https://github.com/bazelbuild/bazel-skylib/releases/tag/0.8.0)
http_archive(
    name = "bazel_skylib",
    sha256 = "f84cc4684a440c2c6b42a818f11388edede8214e20b8476b01727ad8a6d6d4ef",
    strip_prefix = "bazel-skylib-6a6a509f367ca0446e75c6f881719f5da2a55a26",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/6a6a509f367ca0446e75c6f881719f5da2a55a26.zip",
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
