load("@bazel_skylib//rules:build_test.bzl", "build_test")

# Regression tests for particular artifacts that revealed problems for this
# project.

build_test(
    name = "org_pantsbuild_jarjar",
    targets = ["@regression_testing//:org_pantsbuild_jarjar_1_6_6"],
)
