local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    sha256 = "d399f651dbdc5f9116a2da199a808c815c0aeeb8d0b46e3213eee5a41263aeff",
    strip_prefix = "protobuf-3.8.0-rc1",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.8.0-rc1.tar.gz"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

http_archive(
    name = "bazel_skylib",
    sha256 = "2ea8a5ed2b448baf4a6855d3ce049c4c452a6470b1efd1504fdb7c1c134d220a",
    strip_prefix = "bazel-skylib-0.8.0",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/0.8.0.tar.gz"],
)

RULES_SCALA_VERSION = "a676633dc14d8239569affb2acafbef255df3480"

http_archive(
    name = "io_bazel_rules_scala",
    sha256 = "b8b18d0fe3f6c3401b4f83f78f536b24c7fb8b92c593c1dcbcd01cc2b3e85c9a",
    strip_prefix = "rules_scala-%s" % RULES_SCALA_VERSION,
    url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % RULES_SCALA_VERSION,
)

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")

scala_repositories((
    "2.12.8",
    {
        "scala_compiler": "f34e9119f45abd41e85b9e121ba19dd9288b3b4af7f7047e86dc70236708d170",
        "scala_library": "321fb55685635c931eba4bc0d7668349da3f2c09aee2de93a70566066ff25c28",
        "scala_reflect": "4d6405395c4599ce04cea08ba082339e3e42135de9aae2923c9f5367e957315a",
    },
))

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")

scala_register_toolchains()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.github.pureconfig:pureconfig_2.12:0.10.2",
        "com.typesafe.akka:akka-actor_2.12:2.5.22",
        "com.typesafe.akka:akka-http_2.12:10.1.8",
        "com.typesafe.akka:akka-http-testkit_2.12:10.1.8",
        "com.typesafe.akka:akka-stream_2.12:2.5.22",
        "com.typesafe.akka:akka-stream-testkit_2.12:2.5.22",
        "com.typesafe.akka:akka-testkit_2.12:2.5.22",
        "com.typesafe.scala-logging:scala-logging_2.12:3.9.2",
        "org.mockito:mockito-core:2.26.0",
        "org.scalaz:scalaz-core_2.12:7.2.27",
        "org.scalaz:scalaz-concurrent_2.12:7.2.27",
        "org.slf4j:slf4j-api:1.7.26",
        "org.slf4j:slf4j-simple:1.7.26",
    ],
    fetch_sources = True,
    maven_install_json = "//:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)

load("@maven//:defs.bzl", "pinned_maven_install")

pinned_maven_install()
