load("@rules_java//java:defs.bzl", "java_binary")

licenses(["notice"])

java_binary(
    name = "hasher",
    main_class = "rules.jvm.external.Hasher",
    runtime_deps = ["//private/tools/java/rules/jvm/external:hasher"],
)
