
filegroup(
    name = "all_files",
    srcs = glob(["**"]) + [
        "//private/tools/java/com/github/bazelbuild/rules_jvm_external:all_files",
        "//private/tools/prebuilt:all_files",
    ],
    visibility = ["//private:__pkg__"],
)
