load(":coursier_test.bzl", "coursier_test_suite")
load(":proxy_test.bzl", "proxy_test_suite")
load(":specs_test.bzl", "artifact_specs_test_suite")

artifact_specs_test_suite()

coursier_test_suite()

proxy_test_suite()
