load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(
    name = "androidsdk",
)

local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "junit:junit:4.12",
        "com.google.inject:guice:4.0",
        "org.hamcrest:java-hamcrest:2.0.0.0",
        "androidx.test.espresso:espresso-core:3.1.1",
        "androidx.test:runner:1.1.1",
        "androidx.test:rules:1.1.1",
        "androidx.test.ext:junit:1.1.0",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

# Everything below this line is used for the Android testing tools and their dependencies
# ---------------------------------------------------------------------------------------

ATS_TAG = "2e990782519786bca2f8bf23b2c5933f0d69da8d"

http_archive(
    name = "android_test_support",
    sha256 = "de74535cc212a5d9f3e2d24d9a6cf9e1a3734e834563458ad6dd5474dd6aa9c7",
    strip_prefix = "android-test-%s" % ATS_TAG,
    urls = ["https://github.com/android/android-test/archive/%s.tar.gz" % ATS_TAG],
)

load("@android_test_support//:repo.bzl", "android_test_repositories")

android_test_repositories()
